name: Vam api Github Action

on:
    push:
        branches:
            - release

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v3

            - name: Set up Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: '20'

            - name: Install pnpm
              run: npm install -g pnpm

            - name: pnpm install, build, and test
              run: |
                  pnpm install
                  pnpm build

    deploy:
        needs: build
        runs-on: ubuntu-latest

        steps:
            - name: Set up SSH
              uses: webfactory/ssh-agent@v0.5.3
              with:
                  ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

            - name: Deploy to Server
              run: |
                  ssh -o StrictHostKeyChecking=no root@165.227.168.214 << EOF
                    cd /opt/vam/vam-api
                    git pull origin release
                    npm run build 
                    pm2 restart all
                  EOF
